#!/bin/sh

RUN_DIR=$(pwd)
cd $(dirname "$0")
SCRIPT_DIR=$(pwd)

if [ -n "$1" ]; then
  case "$1" in
  EarlyBlue)
    THEME_NAME=$1
    ;;
  LCARStrek)
    THEME_NAME=$1
    ;;
  *)
    echo "unknown theme $option"
    ;;
  esac
else
  echo "You must specify a theme name."
  exit 1
fi

# define variables
THEME_DIR=$SCRIPT_DIR/$THEME_NAME/
WORK_DIR=$SCRIPT_DIR/$THEME_NAME.tmp/
XPI_FILE=$SCRIPT_DIR/$THEME_NAME.xpi

echo ensuring a clean work directory...
if [ -e $WORK_DIR ] ; then
  rm -rf $WORK_DIR/*
fi
mkdir -p $WORK_DIR/chrome

echo copying theme files...
cp -a $THEME_DIR/* $WORK_DIR/
cd $WORK_DIR

echo removing x-* file not intended for shipping...
rm -rf x-*

echo creating new xpi file...
if [ -e $XPI_FILE ] ; then
  rm $XPI_FILE
fi
zip -rX9Dq $XPI_FILE *

echo cleaning work directory...
rm -rf $WORK_DIR
