#!/bin/sh

RUN_DIR=$(pwd)
cd $(dirname "$0")
SCRIPT_DIR=$(pwd)

if [ -n "$1" ]; then
  SRC_DATE="$1"
  DST_DATE=`TZ=America/Los_Angeles date +%Y-%m-%d`

  HG_COMM_DIR=/mnt/mozilla/hg/comm-central
  COMM_DIR=suite/themes/classic/
  COMM_LOG=$RUN_DIR/themelog-suitedefault.$SRC_DATE.$DST_DATE.log

  HG_MOZ_DIR=/mnt/mozilla/hg/comm-central/mozilla
  MOZ_DIR=toolkit/themes/winstripe/
  MOZ_LOG=$RUN_DIR/themelog-tkwinstripe.$SRC_DATE.$DST_DATE.log

  HG_DOMI_DIR=/mnt/mozilla/hg/comm-central/mozilla/extensions/inspector
  DOMI_DIR=resources/skin/classic/
  DOMI_LOG=$RUN_DIR/themelog-domiclassic.$SRC_DATE.$DST_DATE.log

  HG_CZ_DIR=/mnt/mozilla/hg/comm-central/mozilla/extensions/irc
  CZ_DIR=xul/skin/
  CZ_LOG=$RUN_DIR/themelog-chatzilla.$SRC_DATE.$DST_DATE.log

  for repo in "COMM" "MOZ" "DOMI" "CZ"; do
    HG_DIR_VAR="HG_${repo}_DIR"
    HG_DIR=${!HG_DIR_VAR}
    SKIN_DIR_VAR="${repo}_DIR"
    SKIN_DIR=${!SKIN_DIR_VAR}
    LOG_VAR="${repo}_LOG"
    LOG_NAME=${!LOG_VAR}
    if [ ! -e $LOG_NAME ]; then
      echo "Getting $LOG_NAME..."
      cd $HG_DIR
      hg log -d ">$SRC_DATE" $SKIN_DIR > $LOG_NAME
    fi
  done
  cd $RUN_DIR
else
  echo "You must specify a start date."
  exit 1
fi

for repo in "COMM" "MOZ" "DOMI" "CZ"; do
  HG_DIR_VAR="HG_${repo}_DIR"
  LOG_VAR="${repo}_LOG"
  HG_URL=`awk -F ' *= *' '/default *=/ { print $2 }' ${!HG_DIR_VAR}/.hg/hgrc`
  REPO_NAME=`basename $HG_URL`
  LOG_NAME=${!LOG_VAR}
  HTML_NAME=${LOG_NAME/.log/.html}
  echo "Writing $HTML_NAME..."
  echo '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">' > $HTML_NAME
  echo "<html>" >> $HTML_NAME
  echo "  <head>" >> $HTML_NAME
  echo "    <title>$REPO_NAME Theme Changes</title>" >> $HTML_NAME
  echo "  </head>" >> $HTML_NAME
  echo "  <body>" >> $HTML_NAME
  echo "  <h1>$REPO_NAME Theme Changes</h1>" >> $HTML_NAME
  echo "  <h2>$SRC_DATE to $DST_DATE</h2>" >> $HTML_NAME
  echo "    <pre>" >> $HTML_NAME
  sed -e "s/&/\&amp;/g" -e "s/</\&lt;/g" -e "s/>/\&gt;/g" \
      -e "s|\(changeset: *[0-9]*\):\([0-9a-f]*\)|\1:<a href=\"$HG_URL/rev/\2\">\2</a>|" \
      $LOG_NAME >> $HTML_NAME
  echo "    </pre>" >> $HTML_NAME
  echo "  </body>" >> $HTML_NAME
  echo "</html>" >> $HTML_NAME
done

echo "done."
